"""Fix user-employee relationship: remove employee_id from user, add user_id to employee

Revision ID: 0852f6875b30
Revises: 20996c148704
Create Date: 2026-01-06 19:05:26.019538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0852f6875b30'
down_revision: Union[str, Sequence[str], None] = '20996c148704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_employee_id_key'), 'users', type_='unique')
    op.drop_constraint(op.f('fk_users_employee_id'), 'users', type_='foreignkey')
    op.drop_column('users', 'employee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_users_employee_id'), 'users', 'employees', ['employee_id'], ['id'])
    op.create_unique_constraint(op.f('users_employee_id_key'), 'users', ['employee_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
