"""create roles table with FK to users

Revision ID: 5416ad3106f0
Revises: 3971e80d0b07
Create Date: 2025-07-17 11:46:20.988140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5416ad3106f0'
down_revision: Union[str, Sequence[str], None] = '3971e80d0b07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'roles', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='foreignkey')
    # ### end Alembic commands ###
