"""Fix employee-user relationship foreign keys

Revision ID: 788bd2b641f6
Revises: fdab233a4126
Create Date: 2026-01-06 18:57:29.195828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '788bd2b641f6'
down_revision: Union[str, Sequence[str], None] = 'fdab233a4126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'employees', ['user_id'])
    op.create_foreign_key(None, 'employees', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_column('employees', 'user_id')
    # ### end Alembic commands ###
