"""add image_path column to images

Revision ID: 86c7152ab54a
Revises: c9edd9b641e2
Create Date: 2025-07-18 19:08:18.311045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c7152ab54a'
down_revision: Union[str, Sequence[str], None] = 'c9edd9b641e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image_path', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'image_path')
    # ### end Alembic commands ###
