"""create image and image_category tables

Revision ID: a08ff043bea4
Revises: 552c88c32bed
Create Date: 2025-07-18 16:39:24.667566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a08ff043bea4'
down_revision: Union[str, Sequence[str], None] = '552c88c32bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    # op.drop_table('categories')
    op.drop_constraint(op.f('images_category_id_fkey'), 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'imagecategories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key(op.f('images_category_id_fkey'), 'images', 'categories', ['category_id'], ['id'])
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('categories_created_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('categories_updated_by_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_pkey'))
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    # ### end Alembic commands ###
